# Generated by Django 5.2.8 on 2025-11-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=100)),
                ('subject_name', models.CharField(max_length=100)),
                ('instruction', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
    ]
